SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE SUBSTR(S.SALES_DATE,1,7) = '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC