SELECT A.AUTHOR_ID, 
A.AUTHOR_NAME, 
B.CATEGORY, 
SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES S
INNER JOIN BOOK B USING(BOOK_ID)
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC