WITH AVG_REVIEW AS(
    SELECT 
        REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM
        REST_REVIEW

    GROUP BY REST_ID
)

SELECT 
    A.REST_ID, 
    A.REST_NAME, 
    A.FOOD_TYPE, 
    A.FAVORITES, 
    A.ADDRESS, 
    B.SCORE

FROM REST_INFO A, AVG_REVIEW B
WHERE
    A.REST_ID = B.REST_ID AND
    ADDRESS LIKE "서울%"
ORDER BY B.SCORE DESC, A.FAVORITES DESC