SELECT 
    H.HISTORY_ID, 
    ROUND((TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1)*C.DAILY_FEE*((100-IFNULL(P.DISCOUNT_RATE,0)))/100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
INNER JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON H.CAR_ID = C.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE
        AND CASE
            WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE ''
        END = P.DURATION_TYPE
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC