SELECT 
   CASE WHEN EXISTS(SELECT S.CODE
             FROM SKILLCODES S
             WHERE S.CODE&D.SKILL_CODE
             AND S.CATEGORY = 'Front End') 
             AND EXISTS(SELECT S.CODE
             FROM SKILLCODES S
             WHERE S.CODE&D.SKILL_CODE
             AND S.NAME = 'Python') THEN 'A'
       WHEN EXISTS(SELECT S.CODE
             FROM SKILLCODES S
             WHERE S.CODE&D.SKILL_CODE
             AND S.NAME = 'C#') THEN 'B'
       WHEN EXISTS(SELECT S.CODE
             FROM SKILLCODES S
             WHERE S.CODE&D.SKILL_CODE
             AND S.CATEGORY = 'Front End') THEN 'C'
       END AS GRADE,
       ID, EMAIL
FROM DEVELOPERS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID